"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import {FileText,HelpCircle,LogOut,Newspaper,Package,Plus,Trash2} from "lucide-react";import {getSupabaseClient,isSupabaseConfigured} from "@/lib/supabase/client";import {demoFaqs,demoNews,demoPosts,demoServices} from "@/lib/content";
const modules=[{id:"services",label:"Servicios",icon:Package},{id:"posts",label:"Blog",icon:FileText},{id:"news",label:"Noticias",icon:Newspaper},{id:"faqs",label:"FAQ",icon:HelpCircle}] as const;type ModuleId=typeof modules[number]["id"];const fallback={services:demoServices,posts:demoPosts,news:demoNews,faqs:demoFaqs};
// Dashboard CRUD reutilizable. RLS vuelve a validar cada escritura en la base.
export default function AdminPage(){
 const router=useRouter(),client=getSupabaseClient();const[ready,setReady]=useState(!client);const[active,setActive]=useState<ModuleId>("services");const[rows,setRows]=useState<Record<string,unknown>[]>(fallback.services as unknown as Record<string,unknown>[]);const[message,setMessage]=useState("");
 useEffect(()=>{client?.auth.getSession().then(({data})=>{if(!data.session)router.replace("/admin/login");else setReady(true)})},[client,router]);
 useEffect(()=>{if(!ready||!client)return;client.from(active).select("*").order(active==="faqs"?"sort_order":"created_at",{ascending:false}).then(({data,error})=>{setRows(data??[]);if(error)setMessage(error.message)})},[active,ready,client]);
 function changeModule(id:ModuleId){setActive(id);setMessage("");if(!client)setRows(fallback[id] as unknown as Record<string,unknown>[])}
 async function createItem(){if(!client){setMessage("Conecta Supabase para crear contenido real.");return}const payload=active==="faqs"?{question:"Nueva pregunta",answer:"Escribe una respuesta",sort_order:rows.length+1}:{title:"Nuevo contenido",slug:`nuevo-${Date.now()}`,summary:"Edita este resumen",body:"",is_published:false};const{data,error}=await client.from(active).insert(payload).select().single();if(error)setMessage(error.message);else setRows([data,...rows])}
 async function remove(id:unknown){if(!client||typeof id!=="string"){setMessage("Acción disponible al conectar Supabase.");return}if(!confirm("¿Eliminar este contenido?"))return;const{error}=await client.from(active).delete().eq("id",id);if(error)setMessage(error.message);else setRows(rows.filter(r=>r.id!==id))}
 async function logout(){await client?.auth.signOut();router.replace("/admin/login")}
 if(!ready)return <main className="admin-shell"><section className="admin-card">Validando sesión…</section></main>;
 return <main className="admin-layout"><aside className="admin-sidebar"><p className="eyebrow">CMS Nexo</p><h2>Contenido</h2><nav className="admin-nav">{modules.map(m=><button className={`chip ${active===m.id?"active":""}`} key={m.id} onClick={()=>changeModule(m.id)}><m.icon size={15}/> {m.label}</button>)}</nav><button className="button button-secondary" style={{marginTop:"1rem"}} onClick={logout}><LogOut size={16}/> Salir</button></aside><section className="admin-main"><div className="stat-grid">{modules.map(m=><div className="stat-card" key={m.id}><span>{m.label}</span><strong>{active===m.id?rows.length:"—"}</strong></div>)}</div><div className="section"><div className="admin-toolbar"><div><p className="eyebrow">Editor</p><h1>{modules.find(m=>m.id===active)?.label}</h1></div><button className="button button-primary" onClick={createItem}><Plus size={17}/> Crear</button></div>{!isSupabaseConfigured()&&<p className="notice">Vista de demostración. Configura Supabase para habilitar operaciones persistentes.</p>}{message&&<p className="notice" role="status">{message}</p>}<div style={{overflowX:"auto"}}><table className="admin-table"><thead><tr><th>Título / pregunta</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}><td>{String(row.title??row.question??"Sin título")}</td><td>{row.is_published===false?"Borrador":"Publicado"}</td><td><button className="icon-button" onClick={()=>remove(row.id)} aria-label="Eliminar"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></div></section></main>
}
