-- Contenido inicial de las páginas administrables.
-- El upsert hace que la migración sea repetible sin duplicar registros.
insert into public.pages (slug,title,summary,body,seo_title,seo_description,locale,is_published)
values
('home','Una base sólida para convertir ideas en productos reales.','Arquitectura moderna, contenido administrable y seguridad desde el primer despliegue. Diseñada para operar rápido en cualquier región.','Publica, mide y mejora sin rehacer tu base.','Nexo | Plataforma digital moderna','Base full-stack moderna con CMS, seguridad y despliegue global en Cloudflare.','es-CL',true),
('nosotros','Construimos con intención, no por inercia.','Un equipo multidisciplinario que combina estrategia, diseño y tecnología para resolver problemas importantes.',E'## Nuestra historia\nNacimos para acortar la distancia entre una buena idea y un producto confiable.\n\n## Misión\nCrear soluciones claras, inclusivas y medibles que mejoren decisiones y experiencias.\n\n## Visión\nSer el socio técnico que convierte complejidad en progreso sostenible.','Quiénes somos','Conoce la misión, visión y equipo detrás de Nexo.','es-CL',true),
('privacidad','Política de privacidad','Última actualización: 17 de septiembre de 2026.',E'## Datos que tratamos\nRecopilamos únicamente los datos necesarios para prestar el servicio, proteger las cuentas y mejorar la experiencia.\n\n## Base y finalidad\nEl tratamiento se basa en el consentimiento, la ejecución del servicio y obligaciones legales aplicables. No vendemos información personal.\n\n## Tus derechos\nPuedes solicitar acceso, rectificación, portabilidad o eliminación de tus datos, sujeto a las normas aplicables, incluyendo RGPD y CCPA.\n\n## Cookies\nLas cookies esenciales mantienen la sesión. Las analíticas opcionales requieren consentimiento previo.','Política de privacidad','Información sobre privacidad y tratamiento de datos.','es-CL',true),
('terminos','Términos de servicio','Última actualización: 17 de septiembre de 2026.',E'## Aceptación\nAl utilizar el servicio aceptas estos términos y las políticas vinculadas.\n\n## Uso permitido\nNo puedes vulnerar la seguridad, interferir con el servicio ni utilizarlo para actividades ilícitas.\n\n## Disponibilidad\nTrabajamos para mantener una alta disponibilidad, aunque pueden existir ventanas de mantenimiento y eventos externos.\n\n## Responsabilidad\nLa responsabilidad se limita en la medida permitida por la legislación aplicable.','Términos de servicio','Condiciones generales para el uso del servicio.','es-CL',true)
on conflict (slug) do update set
 title=excluded.title,summary=excluded.summary,body=excluded.body,
 seo_title=excluded.seo_title,seo_description=excluded.seo_description,
 locale=excluded.locale,is_published=excluded.is_published;
